import igraph as ig
import json

GRAPH_PATH = "data/fin_data/graph.graphml"
G = ig.Graph.Read_GraphML(GRAPH_PATH)
CID_TO_IDX = {v["id"]: v.index for v in G.vs}

def highest_degree(in_deg=False,out_deg=False):

    total_degrees = G.degree()

    if in_deg:
        degrees = G.degree(mode="in")
    elif out_deg:
        degrees = G.degree(mode="out")
    else:
        degrees = total_degrees

    order = sorted(range(G.vcount()), key=lambda i: total_degrees[i], reverse=True)

    highest_degree_nodes = [{"id": G.vs[i]["id"], "degree": degrees[i], **G.vs[i].attributes()} for i in order]

    return highest_degree_nodes

# Takes the data output files generated by other analysis functions and updates node attributes with them
def update_data():
    with open("hidinf.json", "r") as f:
        hidden_influence = json.load(f)

    with open("betweenness.json", "r") as f:
        betweenness = json.load(f)

    for node in hidden_influence:
        id = node["id"]
        v = G.vs[CID_TO_IDX[id]]
        v["hidden_influence"] = node["score"]
    for node in betweenness:
        id = node["id"]
        v = G.vs[CID_TO_IDX[id]]
        v["betweenness"] = node["betweenness"]

    G.write_graphml("UPDATEDGRAPH.graphml", prefixattr=False)